### PR TITLE
adding relaxed and sequential phylip formats

### PR DESCRIPTION
**Pull request by Zsailer**
Adding two new reading/writing format methods:

1. `read_phylip_relaxed` 
2. `read_phylip_sequential`

This addresses #25.

@ClaudiaPaetzold, if you have a chance at some point, I'd love to hear if this works for your data.

### CODE REVIEW

**Comment by ClaudiaPaetzold** [comment]
@Zsailer, I had a chance to test the changes, but unfortunately it is still putting out the same error. Could that be because, Bio.SeqIO does not support relaxed/sequential/interleaved phylip, but just the strict one?

**Comment by ClaudiaPaetzold** [comment]
@Zsailer 
I tested it intensely on several files and found that my original file was corrupt. On an intact relaxed phylip file, the changes work perfectly. You can merge them. Thank you.

**Comment by Zsailer** [comment]
Great! Thanks @ClaudiaPaetzold. 

The Biopython docs say that `Bio.AlignIO` supports relaxed and sequential phylip. Interestingly, it appears that `Bio.SeqIO` also supports them, even though the docs don't mention it.

**Comment by Zsailer** [comment]
Merging this PR! Thanks for all your testing @ClaudiaPaetzold!

**Pull request merged**
