### PR TITLE
add requirements to setup.py

### PR DESCRIPTION
**Pull request by safay**
Updates `setup.py` to include requirements from `requirements.txt`.
Deletes `requirements.txt`.

### CODE REVIEW

**Comment by Zsailer** [comment]
Great, thank you @safay! 👍 

I think we should keep the `requirements.txt` file, though. There are a couple reasons why this might be a good idea.

1. It will allow the tests to pass (Travis CI requires a requirements.txt). I'll need to refactor the set up to fix the test problem.
2. I may add a Binder tag at some point and I'll need a requirements.txt for that.
3. I still think it's useful for explicitly listing out requirements in a separate file in the Github repo. Often developers look there for dependencies.

**Comment by safay** [comment]
@Zsailer 
`requirements.txt` is restored.  LMK if there's anything else needed here.  Thanks for being so welcoming to your projects.

**Comment by safay** [comment]
@Zsailer Actually, hold on before merging. What do you think about `setup.py` reading in the `requirements.txt`?  That way the list in `install_requires=` won't be able to get out of sync with `requirements.txt`.

**Comment by Zsailer** [comment]
I did some (quick) reading about the `requirements.txt` versus `install_requires` and it looks like they really should be separate. See this (docs page)[https://packaging.python.org/discussions/install-requires-vs-requirements/]. 

The `requirements.txt` should probably include more items that set up a complete environment for running phylopandas. In fact, I think we should also add a [Binder](https://mybinder.org/) for this package pointing to the intro-notebook. Then, the `requirements.txt` file would set up the environment for the Binder. What do you think?

**Comment by safay** [comment]
@Zsailer This is a useful link, it really helps to clarify.  I think Binder is a great idea for a tutorial notebook.  I'll make a separate issue for it.  Then we can merge this PR and deal with that separately.  How's that sound?

**Comment by Zsailer** [comment]
That sounds great. Thank you! 

Merging this PR now.

**Pull request merged**
